/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MedicalRouteImport } from './routes/medical'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GriefSupportRouteImport } from './routes/grief-support'
import { Route as GardenRouteImport } from './routes/garden'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as AdoptionRouteImport } from './routes/adoption'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CreateIndexRouteImport } from './routes/create.index'
import { Route as UUserIdRouteImport } from './routes/u.$userId'
import { Route as MemorialSlugRouteImport } from './routes/memorial.$slug'
import { Route as CreateMemorialRouteImport } from './routes/create.memorial'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedJournalRouteImport } from './routes/_authenticated/journal'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedMemorialSlugEditRouteImport } from './routes/_authenticated/memorial.$slug.edit'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicalRoute = MedicalRouteImport.update({
  id: '/medical',
  path: '/medical',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GriefSupportRoute = GriefSupportRouteImport.update({
  id: '/grief-support',
  path: '/grief-support',
  getParentRoute: () => rootRouteImport,
} as any)
const GardenRoute = GardenRouteImport.update({
  id: '/garden',
  path: '/garden',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const AdoptionRoute = AdoptionRouteImport.update({
  id: '/adoption',
  path: '/adoption',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateIndexRoute = CreateIndexRouteImport.update({
  id: '/create/',
  path: '/create/',
  getParentRoute: () => rootRouteImport,
} as any)
const UUserIdRoute = UUserIdRouteImport.update({
  id: '/u/$userId',
  path: '/u/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const MemorialSlugRoute = MemorialSlugRouteImport.update({
  id: '/memorial/$slug',
  path: '/memorial/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateMemorialRoute = CreateMemorialRouteImport.update({
  id: '/create/memorial',
  path: '/create/memorial',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedJournalRoute = AuthenticatedJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMemorialSlugEditRoute =
  AuthenticatedMemorialSlugEditRouteImport.update({
    id: '/memorial/$slug/edit',
    path: '/memorial/$slug/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/adoption': typeof AdoptionRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/garden': typeof GardenRoute
  '/grief-support': typeof GriefSupportRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/medical': typeof MedicalRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/journal': typeof AuthenticatedJournalRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/create/memorial': typeof CreateMemorialRoute
  '/memorial/$slug': typeof MemorialSlugRoute
  '/u/$userId': typeof UUserIdRoute
  '/create/': typeof CreateIndexRoute
  '/memorial/$slug/edit': typeof AuthenticatedMemorialSlugEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/adoption': typeof AdoptionRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/garden': typeof GardenRoute
  '/grief-support': typeof GriefSupportRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/medical': typeof MedicalRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/journal': typeof AuthenticatedJournalRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/create/memorial': typeof CreateMemorialRoute
  '/memorial/$slug': typeof MemorialSlugRoute
  '/u/$userId': typeof UUserIdRoute
  '/create': typeof CreateIndexRoute
  '/memorial/$slug/edit': typeof AuthenticatedMemorialSlugEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/adoption': typeof AdoptionRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/garden': typeof GardenRoute
  '/grief-support': typeof GriefSupportRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/medical': typeof MedicalRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRoute
  '/signup': typeof SignupRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/journal': typeof AuthenticatedJournalRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/create/memorial': typeof CreateMemorialRoute
  '/memorial/$slug': typeof MemorialSlugRoute
  '/u/$userId': typeof UUserIdRoute
  '/create/': typeof CreateIndexRoute
  '/_authenticated/memorial/$slug/edit': typeof AuthenticatedMemorialSlugEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/adoption'
    | '/community'
    | '/contact'
    | '/garden'
    | '/grief-support'
    | '/login'
    | '/marketplace'
    | '/medical'
    | '/privacy'
    | '/resources'
    | '/signup'
    | '/dashboard'
    | '/journal'
    | '/notifications'
    | '/settings'
    | '/create/memorial'
    | '/memorial/$slug'
    | '/u/$userId'
    | '/create/'
    | '/memorial/$slug/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/adoption'
    | '/community'
    | '/contact'
    | '/garden'
    | '/grief-support'
    | '/login'
    | '/marketplace'
    | '/medical'
    | '/privacy'
    | '/resources'
    | '/signup'
    | '/dashboard'
    | '/journal'
    | '/notifications'
    | '/settings'
    | '/create/memorial'
    | '/memorial/$slug'
    | '/u/$userId'
    | '/create'
    | '/memorial/$slug/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/admin'
    | '/adoption'
    | '/community'
    | '/contact'
    | '/garden'
    | '/grief-support'
    | '/login'
    | '/marketplace'
    | '/medical'
    | '/privacy'
    | '/resources'
    | '/signup'
    | '/_authenticated/dashboard'
    | '/_authenticated/journal'
    | '/_authenticated/notifications'
    | '/_authenticated/settings'
    | '/create/memorial'
    | '/memorial/$slug'
    | '/u/$userId'
    | '/create/'
    | '/_authenticated/memorial/$slug/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AdoptionRoute: typeof AdoptionRoute
  CommunityRoute: typeof CommunityRoute
  ContactRoute: typeof ContactRoute
  GardenRoute: typeof GardenRoute
  GriefSupportRoute: typeof GriefSupportRoute
  LoginRoute: typeof LoginRoute
  MarketplaceRoute: typeof MarketplaceRoute
  MedicalRoute: typeof MedicalRoute
  PrivacyRoute: typeof PrivacyRoute
  ResourcesRoute: typeof ResourcesRoute
  SignupRoute: typeof SignupRoute
  CreateMemorialRoute: typeof CreateMemorialRoute
  MemorialSlugRoute: typeof MemorialSlugRoute
  UUserIdRoute: typeof UUserIdRoute
  CreateIndexRoute: typeof CreateIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medical': {
      id: '/medical'
      path: '/medical'
      fullPath: '/medical'
      preLoaderRoute: typeof MedicalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grief-support': {
      id: '/grief-support'
      path: '/grief-support'
      fullPath: '/grief-support'
      preLoaderRoute: typeof GriefSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garden': {
      id: '/garden'
      path: '/garden'
      fullPath: '/garden'
      preLoaderRoute: typeof GardenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adoption': {
      id: '/adoption'
      path: '/adoption'
      fullPath: '/adoption'
      preLoaderRoute: typeof AdoptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/': {
      id: '/create/'
      path: '/create'
      fullPath: '/create/'
      preLoaderRoute: typeof CreateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$userId': {
      id: '/u/$userId'
      path: '/u/$userId'
      fullPath: '/u/$userId'
      preLoaderRoute: typeof UUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memorial/$slug': {
      id: '/memorial/$slug'
      path: '/memorial/$slug'
      fullPath: '/memorial/$slug'
      preLoaderRoute: typeof MemorialSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/memorial': {
      id: '/create/memorial'
      path: '/create/memorial'
      fullPath: '/create/memorial'
      preLoaderRoute: typeof CreateMemorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/journal': {
      id: '/_authenticated/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof AuthenticatedJournalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/memorial/$slug/edit': {
      id: '/_authenticated/memorial/$slug/edit'
      path: '/memorial/$slug/edit'
      fullPath: '/memorial/$slug/edit'
      preLoaderRoute: typeof AuthenticatedMemorialSlugEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedJournalRoute: typeof AuthenticatedJournalRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedMemorialSlugEditRoute: typeof AuthenticatedMemorialSlugEditRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedJournalRoute: AuthenticatedJournalRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedMemorialSlugEditRoute: AuthenticatedMemorialSlugEditRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AdoptionRoute: AdoptionRoute,
  CommunityRoute: CommunityRoute,
  ContactRoute: ContactRoute,
  GardenRoute: GardenRoute,
  GriefSupportRoute: GriefSupportRoute,
  LoginRoute: LoginRoute,
  MarketplaceRoute: MarketplaceRoute,
  MedicalRoute: MedicalRoute,
  PrivacyRoute: PrivacyRoute,
  ResourcesRoute: ResourcesRoute,
  SignupRoute: SignupRoute,
  CreateMemorialRoute: CreateMemorialRoute,
  MemorialSlugRoute: MemorialSlugRoute,
  UUserIdRoute: UUserIdRoute,
  CreateIndexRoute: CreateIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
